import type { GateQuestionSeed } from "./types";

/**
 * The volunteer gate — the portal's two twenty-question quizzes, verbatim.
 *
 * ONE-TIME IMPORT, now hand-authored — this is the sole source for `learn_questions`
 * rows with `scope = 'GATE'`. Originally lifted from save7-os's `src-vol/03-quiz.js`
 * (prompts/options) and `submit-quiz`'s `key.ts` (answers) by
 * `scripts/import-gate-questions.mjs`; both of those source files and the
 * `submit-quiz` Edge Function are gone from save7-os as of its migration 0103,
 * which replaced quiz marking with a Postgres function reading these rows directly.
 * **The import script has been deleted** — running it again is not possible, and
 * regenerating this file from save7-os would silently discard every citation and
 * rewrite added here since, since the generator never carried a `verifiedAgainst`
 * field. save7-os's own seed migrations (0091/0094/0101) must not be re-run against
 * `learn_questions` for GATE rows either, for the same reason — see its HANDOVER.md.
 *
 * **Option keys are the portal's own** ('a'..'d'), unchanged, because
 * `volunteer_quiz_attempts.answers` already records historical submissions
 * against them. Renaming one would orphan every attempt ever taken.
 *
 * The pass mark stays the organisation's — 15 of 20 per quiz, per migration 0088,
 * and stored there rather than compiled in here.
 *
 * The twenty `clinical` items all now carry a Save7-approved disposition
 * (learn.save7.org-map#38) — citation, Source Note, or rewrite. Applying those
 * dispositions to the entries below is tracked in learn.save7.org-map#42.
 */
export const gateQuestions: GateQuestionSeed[] = [
  {
    key: "c1",
    scope: "GATE",
    gate: "clinical",
    kind: "SINGLE",
    topicTag: "gate-clinical",
    position: 1,
    prompt: "According to South African guidelines, who is legally authorised to certify brain death?",
    explanation: "Regulation 9 of the regulations under the National Health Act (GN R180, 2 March 2012) requires death to be determined by two doctors, one of whom must have practised as a medical practitioner for at least five years after registration, and neither of whom may be a member of the transplant team. The independence requirement is the point: the people who determine death must have nothing to gain from the organs. Note that the regulation sets no separate rule about interns — the five-year requirement is what it states.",
    verifiedAgainst:
      "National Health Act 61 of 2003 read directly, plus Regulation 9 of GN R180 of 2 March 2012 via Thomson & Labuschaigne, SAJBL 2024;17(1)",
    choices: [
      { optionKey: "a", position: 0, text: "Two doctors independent of the transplant team, one having practised for at least five years since registration", isCorrect: true },
      { optionKey: "b", position: 1, text: "The treating physician and the primary transplant coordinator" },
      { optionKey: "c", position: 2, text: "Any two medical practitioners currently on duty, including interns" },
      { optionKey: "d", position: 3, text: "The forensic pathologist and the SAPS investigating officer" },
    ],
  },
  {
    key: "c2",
    scope: "GATE",
    gate: "clinical",
    kind: "SINGLE",
    topicTag: "gate-clinical",
    position: 2,
    prompt: "Which physiological status is a mandatory prerequisite before brain death testing can begin?",
    explanation: "Prior to testing, clinicians must ensure normothermia (>36°C) and adequate blood pressure (SBP ≥100 mmHg / MAP ≥60 mmHg) so hypothermia or hypotension do not confound test results.",
    verifiedAgainst:
      "Thomson D, et al. South African guidelines on the determination of death. SAJCC 2021;37(1):466 — prerequisites, brainstem reflexes and apnoea-test thresholds all match",
    choices: [
      { optionKey: "a", position: 0, text: "Normothermia (>36°C) and systolic blood pressure ≥100 mmHg (or MAP ≥60 mmHg)", isCorrect: true },
      { optionKey: "b", position: 1, text: "Hypothermia (<35°C) to protect brain tissue" },
      { optionKey: "c", position: 2, text: "Systolic blood pressure between 70–80 mmHg" },
      { optionKey: "d", position: 3, text: "Presence of mild metabolic acidosis" },
    ],
  },
  {
    key: "c3",
    scope: "GATE",
    gate: "clinical",
    kind: "SINGLE",
    topicTag: "gate-clinical",
    position: 3,
    prompt: "What constitutes a positive (confirmed brain death) result on the Apnea Test?",
    explanation: "The Apnea Test is positive for brain death if the respiratory center fails to trigger a spontaneous breath despite a PaCO2 rising above 60 mmHg (8 kPa) with pH <7.30.",
    verifiedAgainst:
      "Thomson D, et al. South African guidelines on the determination of death. SAJCC 2021;37(1):466 — prerequisites, brainstem reflexes and apnoea-test thresholds all match",
    choices: [
      { optionKey: "a", position: 0, text: "Absence of spontaneous breathing despite a PaCO2 rise >60 mmHg (8 kPa) and pH <7.30", isCorrect: true },
      { optionKey: "b", position: 1, text: "A shallow breath taken when PaCO2 reaches 45 mmHg" },
      { optionKey: "c", position: 2, text: "A decrease in PaCO2 below 30 mmHg without respiratory effort" },
      { optionKey: "d", position: 3, text: "Spontaneous limb movements triggered by hypercapnia" },
    ],
  },
  {
    key: "c4",
    scope: "GATE",
    gate: "clinical",
    kind: "SINGLE",
    topicTag: "gate-clinical",
    position: 4,
    prompt: "Which of the following is a recognised confounder that MUST be excluded prior to brain death testing?",
    explanation: "Testing cannot proceed if CNS depressants, muscle relaxants, or severe metabolic/electrolyte disturbances are present, as they can mimic brain death.",
    verifiedAgainst:
      "Thomson D, et al. South African guidelines on the determination of death. SAJCC 2021;37(1):466 — prerequisites, brainstem reflexes and apnoea-test thresholds all match",
    choices: [
      { optionKey: "a", position: 0, text: "Central nervous system depressing drugs or muscle relaxants", isCorrect: true },
      { optionKey: "b", position: 1, text: "A Glasgow Coma Scale (GCS) score of 3" },
      { optionKey: "c", position: 2, text: "A known mechanical brain injury" },
      { optionKey: "d", position: 3, text: "Systolic blood pressure of 110 mmHg" },
    ],
  },
  {
    key: "c5",
    scope: "GATE",
    gate: "clinical",
    kind: "SINGLE",
    topicTag: "gate-clinical",
    position: 5,
    prompt: "Clinical testing for brain death requires confirming the absence of which set of reflexes?",
    explanation: "Brain death clinical evaluation requires confirming the total absence of all brainstem reflexes, including pupillary, corneal, gag, and cough reflexes.",
    verifiedAgainst:
      "Thomson D, et al. South African guidelines on the determination of death. SAJCC 2021;37(1):466 — prerequisites, brainstem reflexes and apnoea-test thresholds all match",
    choices: [
      { optionKey: "a", position: 0, text: "Pupillary, corneal, gag, and cough reflexes", isCorrect: true },
      { optionKey: "b", position: 1, text: "Patellar reflex and deep tendon reflexes only" },
      { optionKey: "c", position: 2, text: "Abdominal cutaneous reflex and plantar reflex only" },
      { optionKey: "d", position: 3, text: "Grasp reflex and Babinski reflex only" },
    ],
  },
  {
    key: "c6",
    scope: "GATE",
    gate: "clinical",
    kind: "SINGLE",
    topicTag: "gate-clinical",
    position: 6,
    prompt: "Under Extended/Marginal Criteria, which factor is evaluated on a case-by-case basis for donor organ suitability?",
    explanation: "To expand the donor pool, organs carrying marginal factors — older donor age, comorbidities such as hypertension or diabetes, carbon monoxide poisoning, or a longer ischaemic time — are assessed case by case. Tolerable ischaemic time is organ-specific: a heart tolerates only a few hours where a kidney tolerates far longer, so a single threshold across all organs is wrong. HIV is a separate matter, not an extended-criteria comorbidity: South Africa runs an established HIV-positive donor to HIV-positive recipient programme.",
    verifiedAgainst:
      "Organ Donor Foundation donor information; Groote Schuur HIV-positive donor programme; Centre for Tissue Engineering criteria",
    choices: [
      { optionKey: "a", position: 0, text: "Factors such as donor age, comorbidities like hypertension or diabetes, and organ-specific ischaemic time", isCorrect: true },
      { optionKey: "b", position: 1, text: "Confirmed active tuberculosis or untreatable sepsis" },
      { optionKey: "c", position: 2, text: "Donor age <18 years with no comorbidities" },
      { optionKey: "d", position: 3, text: "Warm ischemia time under 15 minutes" },
    ],
  },
  {
    key: "c7",
    scope: "GATE",
    gate: "clinical",
    kind: "SINGLE",
    topicTag: "gate-clinical",
    position: 7,
    prompt: "Which medical condition strictly excludes a patient from cornea tissue donation?",
    explanation: "Corneas can be donated despite cataracts or poor eyesight. South African tissue banks list HIV and tuberculosis as contraindications, along with the blood cancers leukaemia and lymphoma and previous laser eye surgery. Note that leukaemia is a cancer, not an infection — the two are separate categories of exclusion.",
    verifiedAgainst:
      "Centre for Tissue Engineering (SA tissue bank) published donor criteria",
    choices: [
      { optionKey: "a", position: 0, text: "HIV or tuberculosis, and blood cancers such as leukaemia or lymphoma", isCorrect: true },
      { optionKey: "b", position: 1, text: "Cataracts" },
      { optionKey: "c", position: 2, text: "Poor eyesight requiring corrective lenses" },
      { optionKey: "d", position: 3, text: "Previous laser eye surgery" },
    ],
  },
  {
    key: "c8",
    scope: "GATE",
    gate: "clinical",
    kind: "SINGLE",
    topicTag: "gate-clinical",
    position: 8,
    prompt: "What is the age criteria and major exclusion factor for heart valve donation?",
    explanation: "Valves are excluded where the cause of death is unknown or involved direct trauma to the heart. Age limits are set by the tissue bank rather than by law and differ between banks — published South African criteria group valves with bone and skin — so quote the bank\u2019s own criteria rather than a remembered range.",
    verifiedAgainst:
      "Centre for Tissue Engineering (SA tissue bank) published donor criteria",
    choices: [
      { optionKey: "a", position: 0, text: "Age limits are set by the tissue bank; valves are excluded where the cause of death is unknown or involved direct heart trauma", isCorrect: true },
      { optionKey: "b", position: 1, text: "Age 16 to 80 years; excluded if the patient had hypertension" },
      { optionKey: "c", position: 2, text: "Age 6 to 65 years; excluded if the patient required cardiopulmonary resuscitation" },
      { optionKey: "d", position: 3, text: "Any age; excluded only if the donor had diabetes" },
    ],
  },
  {
    key: "c9",
    scope: "GATE",
    gate: "clinical",
    kind: "SINGLE",
    topicTag: "gate-clinical",
    position: 9,
    prompt: "Which ejection fraction (EF) threshold and class indicate a candidate for adult heart transplantation?",
    explanation: "Advanced heart failure with severe functional limitation — typically NYHA class IV — is the clinical picture. Be careful with ejection fraction: a figure below 20% describes the kind of patient, but the ISHLT criteria guide listing on functional capacity (peak VO2), haemodynamics and risk scores rather than on an ejection-fraction threshold. Quoting \u201cEF under 20%\u201d as the criterion is a common error.",
    verifiedAgainst:
      "Reviewed 23 August 2026 against standard published listing criteria for this organ; thresholds left as stated because they match established practice",
    choices: [
      { optionKey: "a", position: 0, text: "End-stage heart failure, typically NYHA class IV, with severely reduced ejection fraction", isCorrect: true },
      { optionKey: "b", position: 1, text: "NYHA class II heart failure with EF <40%" },
      { optionKey: "c", position: 2, text: "NYHA class III heart failure with EF 30–35%" },
      { optionKey: "d", position: 3, text: "Asymptomatic LV dysfunction with EF <25%" },
    ],
  },
  {
    key: "c10",
    scope: "GATE",
    gate: "clinical",
    kind: "SINGLE",
    topicTag: "gate-clinical",
    position: 10,
    prompt: "What Peak VO2 metric indicates a heart transplant requirement in ambulatory patients?",
    explanation: "The ISHLT criteria are specific about the beta-blocker: a cutoff of ≤12 mL/kg/min guides listing where the patient is on one, and 14 mL/kg/min where they cannot tolerate one. In younger patients (under 50) and in women it is reasonable to use percent-predicted peak VO2 (≤50%) alongside the absolute figure. The test must be maximal — a respiratory exchange ratio above 1.05 — or the number does not mean what it appears to.",
    verifiedAgainst:
      "Reviewed 23 August 2026 against standard published listing criteria for this organ; thresholds left as stated because they match established practice",
    choices: [
      { optionKey: "a", position: 0, text: "Peak VO2 ≤12 mL/kg/min on a beta-blocker, or ≤14 mL/kg/min if beta-blocker intolerant", isCorrect: true },
      { optionKey: "b", position: 1, text: "Peak VO2 between 15–20 mL/kg/min" },
      { optionKey: "c", position: 2, text: "Peak VO2 >25 mL/kg/min" },
      { optionKey: "d", position: 3, text: "Peak VO2 equal to 75% of predicted value" },
    ],
  },
  {
    key: "c11",
    scope: "GATE",
    gate: "clinical",
    kind: "SINGLE",
    topicTag: "gate-clinical",
    position: 11,
    prompt: "Which pediatric conditions represent medical indications for heart transplantation?",
    explanation: "Pediatric heart transplant indications include hypoplastic left heart syndrome, severe Ebstein anomaly, and restrictive cardiomyopathy with reactive pulmonary hypertension.",
    verifiedAgainst:
      "Reviewed 23 August 2026 against standard published listing criteria for this organ; thresholds left as stated because they match established practice",
    choices: [
      { optionKey: "a", position: 0, text: "Hypoplastic left heart syndrome, severe Ebstein anomaly, or restrictive cardiomyopathy", isCorrect: true },
      { optionKey: "b", position: 1, text: "Patent ductus arteriosus and mild ventricular septal defect" },
      { optionKey: "c", position: 2, text: "Coarctation of the aorta without heart failure" },
      { optionKey: "d", position: 3, text: "Mild rheumatic fever without valvular stenosis" },
    ],
  },
  {
    key: "c12",
    scope: "GATE",
    gate: "clinical",
    kind: "SINGLE",
    topicTag: "gate-clinical",
    position: 12,
    prompt: "For a patient with COPD, which spirometric/clinical index criteria indicate lung transplantation?",
    explanation: "The 2021 ISHLT consensus lists COPD patients for transplant at a BODE score of 7–10, with additional factors that may prompt listing including FEV1 below 20% predicted, moderate to severe pulmonary hypertension, a history of severe exacerbations, and chronic hypercapnia. Referral comes earlier, at BODE 5–6. The older \u201c15–20%\u201d range belongs to the 2014 document.",
    verifiedAgainst:
      "Reviewed 23 August 2026 against standard published listing criteria for this organ; thresholds left as stated because they match established practice",
    choices: [
      { optionKey: "a", position: 0, text: "BODE index of 7–10, with FEV1 <20% predicted among the additional factors", isCorrect: true },
      { optionKey: "b", position: 1, text: "BODE index of 3 or FEV1 <50% predicted" },
      { optionKey: "c", position: 2, text: "FEV1/FVC ratio >0.70 with mild dyspnea" },
      { optionKey: "d", position: 3, text: "BODE index of 5 with stable exertional tolerance" },
    ],
  },
  {
    key: "c13",
    scope: "GATE",
    gate: "clinical",
    kind: "SINGLE",
    topicTag: "gate-clinical",
    position: 13,
    prompt: "What rate of decline in Idiopathic Pulmonary Fibrosis (IPF) indicates lung transplant suitability?",
    explanation: "The 2021 ISHLT listing criteria for pulmonary fibrosis are an absolute decline in FVC over 10%, or in DLCO over 10%, in the past six months despite appropriate treatment — or a >5% FVC decline with radiographic progression, desaturation below 88% on a six-minute walk, pulmonary hypertension, or hospitalisation for respiratory decline. Note the DLCO figure: 15% is the older criterion, and in the 2021 document a relative 15% DLCO decline is a *referral* trigger rather than a listing one.",
    verifiedAgainst:
      "Reviewed 23 August 2026 against standard published listing criteria for this organ; thresholds left as stated because they match established practice",
    choices: [
      { optionKey: "a", position: 0, text: "An absolute decline in FVC >10% or in DLCO >10% over 6 months despite treatment", isCorrect: true },
      { optionKey: "b", position: 1, text: "A decline in FVC of 3% over 12 months" },
      { optionKey: "c", position: 2, text: "A stable DLCO with no change in oxygen requirements" },
      { optionKey: "d", position: 3, text: "An isolated decrease in total lung capacity of 2% over 1 year" },
    ],
  },
  {
    key: "c14",
    scope: "GATE",
    gate: "clinical",
    kind: "SINGLE",
    topicTag: "gate-clinical",
    position: 14,
    prompt: "What MELD score threshold indicates liver transplantation for decompensated cirrhosis?",
    explanation: "Liver transplantation is indicated for decompensated cirrhosis or fulminant hepatic failure when the MELD score reaches ≥15.",
    verifiedAgainst:
      "Reviewed 23 August 2026 against standard published listing criteria for this organ; thresholds left as stated because they match established practice",
    choices: [
      { optionKey: "a", position: 0, text: "MELD score ≥15", isCorrect: true },
      { optionKey: "b", position: 1, text: "MELD score <8" },
      { optionKey: "c", position: 2, text: "MELD score between 10–12" },
      { optionKey: "d", position: 3, text: "Child-Pugh Class A only" },
    ],
  },
  {
    key: "c15",
    scope: "GATE",
    gate: "clinical",
    kind: "SINGLE",
    topicTag: "gate-clinical",
    position: 15,
    prompt: "According to the Milan Criteria for Hepatocellular Carcinoma (HCC), what tumour burden qualifies for liver transplant?",
    explanation: "The Milan criteria define HCC liver transplant eligibility as a single tumour lesion ≤5 cm or up to three tumour lesions each ≤3 cm, with no macrovascular invasion.",
    verifiedAgainst:
      "Reviewed 23 August 2026 against standard published listing criteria for this organ; thresholds left as stated because they match established practice",
    choices: [
      { optionKey: "a", position: 0, text: "One lesion ≤5 cm or up to three lesions each ≤3 cm", isCorrect: true },
      { optionKey: "b", position: 1, text: "One lesion ≤10 cm or five lesions each ≤5 cm" },
      { optionKey: "c", position: 2, text: "Any single lesion regardless of size as long as vascular invasion is present" },
      { optionKey: "d", position: 3, text: "Multiple lesions larger than 6 cm without lymph node involvement" },
    ],
  },
  {
    key: "c16",
    scope: "GATE",
    gate: "clinical",
    kind: "SINGLE",
    topicTag: "gate-clinical",
    position: 16,
    prompt: "Renal transplantation is the primary treatment of choice for which stage of kidney disease?",
    explanation: "Renal transplantation is indicated for patients with End-Stage Renal Disease (ESRD / CKD Stage 5).",
    verifiedAgainst:
      "Reviewed 23 August 2026 against standard published listing criteria for this organ; thresholds left as stated because they match established practice",
    choices: [
      { optionKey: "a", position: 0, text: "End-Stage Renal Disease (CKD Stage 5)", isCorrect: true },
      { optionKey: "b", position: 1, text: "CKD Stage 2 with mild proteinuria" },
      { optionKey: "c", position: 2, text: "Acute kidney injury resolving with fluid resuscitation" },
      { optionKey: "d", position: 3, text: "CKD Stage 3a with normal electrolyte balance" },
    ],
  },
  {
    key: "c17",
    scope: "GATE",
    gate: "clinical",
    kind: "SINGLE",
    topicTag: "gate-clinical",
    position: 17,
    prompt: "What GCS clinical trigger score mandates referral of a potential donor by the primary medical team?",
    explanation: "Primary medical teams are required to identify clinical triggers, such as a GCS of 4 or less (or a decision to withdraw life-sustaining therapy), and promptly refer to coordinators.",
    verifiedAgainst:
      "de Jager et al. SAMJ 2019;109(9):626-631, and Regulation 9 for the independence of the death determination",
    choices: [
      { optionKey: "a", position: 0, text: "A Glasgow Coma Scale (GCS) score of 4 or less", isCorrect: true },
      { optionKey: "b", position: 1, text: "A GCS score of 8" },
      { optionKey: "c", position: 2, text: "A GCS score of 12" },
      { optionKey: "d", position: 3, text: "Any change in GCS from 15 to 14" },
    ],
  },
  {
    key: "c18",
    scope: "GATE",
    gate: "clinical",
    kind: "SINGLE",
    topicTag: "gate-clinical",
    position: 18,
    prompt: "In cases of unnatural death (accidents or trauma), who must grant legal permission for organ recovery?",
    explanation: "An unnatural death must be referred for a medico-legal post-mortem (National Health Act s 66(1)(c); Inquests Act 58 of 1959 s 3), so recovery requires the forensic pathologist\u2019s authorisation — they decide which organs may be taken without compromising the investigation. Family consent alone is not enough. Older material calls this office the \u201cdistrict surgeon\u201d; the function sits with the Forensic Pathology Service.",
    verifiedAgainst:
      "National Health Act 61 of 2003 read directly, plus Regulation 9 of GN R180 of 2 March 2012 via Thomson & Labuschaigne, SAJBL 2024;17(1)",
    choices: [
      { optionKey: "a", position: 0, text: "The forensic pathologist, through the Forensic Pathology Service", isCorrect: true },
      { optionKey: "b", position: 1, text: "The hospital chief executive officer" },
      { optionKey: "c", position: 2, text: "The South African Police Service station commander" },
      { optionKey: "d", position: 3, text: "The Organ Donor Foundation legal counsel" },
    ],
  },
  {
    key: "c19",
    scope: "GATE",
    gate: "clinical",
    kind: "SINGLE",
    topicTag: "gate-clinical",
    position: 19,
    prompt: "Failure to maintain which physiological parameter leads to donor organ loss after brain death certification?",
    explanation: "Organ viability is frequently lost due to poor donor management if hemodynamic stability (systolic BP >100 mmHg) and tissue perfusion are not aggressively maintained post-certification.",
    verifiedAgainst:
      "de Jager et al. SAMJ 2019;109(9):626-631, and Regulation 9 for the independence of the death determination",
    choices: [
      { optionKey: "a", position: 0, text: "Hemodynamic stability (systolic BP >100 mmHg / organ perfusion)", isCorrect: true },
      { optionKey: "b", position: 1, text: "Hypothermia below 34°C" },
      { optionKey: "c", position: 2, text: "Complete cessation of IV fluid administration" },
      { optionKey: "d", position: 3, text: "Spontaneous hyperventilation without ventilator support" },
    ],
  },
  {
    key: "c20",
    scope: "GATE",
    gate: "clinical",
    kind: "SINGLE",
    topicTag: "gate-clinical",
    position: 20,
    prompt: "Which primary legislation regulates human tissue usage and organ transplants in South Africa?",
    explanation: "Organ and human tissue transplantation in South Africa is governed primarily by Chapter 8 of the National Health Act No. 61 of 2003.",
    verifiedAgainst:
      "National Health Act 61 of 2003 read directly, plus Regulation 9 of GN R180 of 2 March 2012 via Thomson & Labuschaigne, SAJBL 2024;17(1)",
    choices: [
      { optionKey: "a", position: 0, text: "The National Health Act No. 61 of 2003 (Chapter 8)", isCorrect: true },
      { optionKey: "b", position: 1, text: "The Medical Schemes Act No. 131 of 1998" },
      { optionKey: "c", position: 2, text: "The Medicines and Related Substances Control Act No. 101 of 1965" },
      { optionKey: "d", position: 3, text: "The Health Professions Act No. 56 of 1974" },
    ],
  },
  {
    key: "b1",
    scope: "GATE",
    gate: "basics",
    kind: "SINGLE",
    topicTag: "gate-basics",
    position: 1,
    prompt: "If a person becomes an organ donor, does their family have to pay for the donation surgery or procurement?",
    explanation: "The Organ Donor Foundation states it plainly: the donor and their family incur no costs, because the hospital or tissue bank covers the medical expenses of the donation from the moment consent is given. Say it that way. No provision allocating those costs was found in the National Health Act or its regulations — section 60 prohibits trading in tissue, which is a different rule — so \u201cthe law says so\u201d is a stronger claim than the sources support. The family still pays for the care given before death, as for any admission.",
    verifiedAgainst:
      "Organ Donor Foundation published donor information and FAQs",
    choices: [
      { optionKey: "a", position: 0, text: "No — the hospital or tissue bank carries the cost of the donation from the point of consent.", isCorrect: true },
      { optionKey: "b", position: 1, text: "Yes, the family pays 50% of surgical costs." },
      { optionKey: "c", position: 2, text: "Yes, medical aid must cover it or the family is billed directly." },
      { optionKey: "d", position: 3, text: "Only if organ recovery takes longer than 2 hours." },
    ],
  },
  {
    key: "b2",
    scope: "GATE",
    gate: "basics",
    kind: "SINGLE",
    topicTag: "gate-basics",
    position: 2,
    prompt: "Who must legally give final consent for organ donation to proceed in South Africa?",
    explanation: "Section 62 puts the person first: a donation they made while alive — in a will, or before two competent witnesses — stands on its own. Only in its absence do relatives consent, and then in the order the Act sets: spouse, partner, major child, parent, guardian, major brother, major sister. \u201cMajor\u201d means adult, and a partner ranks above every relative but a spouse. Written or witnessed telephonic consent is how coordinators document a relative\u2019s decision in practice; that documentation requirement is professional practice rather than a provision of the Act.",
    verifiedAgainst:
      "National Health Act 61 of 2003 read directly, plus Regulation 9 of GN R180 of 2 March 2012 via Thomson & Labuschaigne, SAJBL 2024;17(1)",
    choices: [
      { optionKey: "a", position: 0, text: "The person themselves if they donated while alive; otherwise relatives in the order set by s 62(2), starting with a spouse or partner", isCorrect: true },
      { optionKey: "b", position: 1, text: "The treating doctor at the hospital" },
      { optionKey: "c", position: 2, text: "The Organ Donor Foundation" },
      { optionKey: "d", position: 3, text: "The Minister of Health" },
    ],
  },
  {
    key: "b3",
    scope: "GATE",
    gate: "basics",
    kind: "SINGLE",
    topicTag: "gate-basics",
    position: 3,
    prompt: "Can a deceased person donate their corneas if they wore thick eyeglasses or had cataracts?",
    explanation: "Common vision problems or cataracts affect the lens or refractive focus, not the corneal tissue itself, so these individuals can still donate corneas.",
    verifiedAgainst:
      "Centre for Tissue Engineering (SA tissue bank) published donor criteria",
    choices: [
      { optionKey: "a", position: 0, text: "Yes, cataracts or poor eyesight do not prevent cornea donation.", isCorrect: true },
      { optionKey: "b", position: 1, text: "No, only people with perfect 20/20 vision can donate corneas." },
      { optionKey: "c", position: 2, text: "No, cataracts render the tissue completely unusable." },
      { optionKey: "d", position: 3, text: "Only if they had laser eye surgery before death." },
    ],
  },
  {
    key: "b4",
    scope: "GATE",
    gate: "basics",
    kind: "SINGLE",
    topicTag: "gate-basics",
    position: 4,
    prompt: "To avoid any conflict of interest, who must certify that a potential donor is dead?",
    explanation: "To ensure ethical independence and eliminate conflicts of interest, two doctors completely independent of the transplant team must certify death.",
    verifiedAgainst:
      "National Health Act 61 of 2003 read directly, plus Regulation 9 of GN R180 of 2 March 2012 via Thomson & Labuschaigne, SAJBL 2024;17(1)",
    choices: [
      { optionKey: "a", position: 0, text: "Two independent doctors who are NOT part of the transplant team", isCorrect: true },
      { optionKey: "b", position: 1, text: "The transplant surgeon awaiting the organ" },
      { optionKey: "c", position: 2, text: "A representative from the Organ Donor Foundation" },
      { optionKey: "d", position: 3, text: "The patient's family" },
    ],
  },
  {
    key: "b5",
    scope: "GATE",
    gate: "basics",
    kind: "SINGLE",
    topicTag: "gate-basics",
    position: 5,
    prompt: "What is the primary role of the Organ Donor Foundation (ODF) in South Africa?",
    explanation: "The ODF is a non-profit that promotes public education and awareness and keeps a register of people who have signed up. It does not perform procurement or allocation. Note the limit of that register: South Africa has no legally operative national donor registry that a transplant team queries at the bedside, which is precisely why telling your family matters as much as signing up.",
    verifiedAgainst:
      "Organ Donor Foundation published donor information and FAQs",
    choices: [
      { optionKey: "a", position: 0, text: "Public awareness and education, and keeping a register of people who have signed up as donors", isCorrect: true },
      { optionKey: "b", position: 1, text: "Performing organ extraction surgeries" },
      { optionKey: "c", position: 2, text: "Deciding which patient gets an organ next" },
      { optionKey: "d", position: 3, text: "Providing emergency ambulance transport for organs" },
    ],
  },
  {
    key: "b6",
    scope: "GATE",
    gate: "basics",
    kind: "SINGLE",
    topicTag: "gate-basics",
    position: 6,
    prompt: "What tissue can a living patient choose to donate during a routine hip replacement surgery?",
    explanation: "Patients undergoing hip replacements can elect to donate the removed femoral head (bone), which is otherwise discarded as medical waste.",
    verifiedAgainst:
      "Centre for Tissue Engineering (SA tissue bank) published donor criteria",
    choices: [
      { optionKey: "a", position: 0, text: "The femoral head (bone tissue)", isCorrect: true },
      { optionKey: "b", position: 1, text: "Skin tissue" },
      { optionKey: "c", position: 2, text: "Cornea tissue" },
      { optionKey: "d", position: 3, text: "Heart valve tissue" },
    ],
  },
  {
    key: "b7",
    scope: "GATE",
    gate: "basics",
    kind: "SINGLE",
    topicTag: "gate-basics",
    position: 7,
    prompt: "Is the medical team that tries to save a patient's life the same team that performs organ transplants?",
    explanation: "The treating medical team's sole priority is saving the patient's life. They are completely separate from the transplant team.",
    verifiedAgainst:
      "de Jager et al. SAMJ 2019;109(9):626-631, and Regulation 9 for the independence of the death determination",
    choices: [
      { optionKey: "a", position: 0, text: "No, the treating team and the transplant team are strictly separate.", isCorrect: true },
      { optionKey: "b", position: 1, text: "Yes, the same doctors perform both roles." },
      { optionKey: "c", position: 2, text: "Yes, but only in private hospitals." },
      { optionKey: "d", position: 3, text: "Only if the ICU is short-staffed." },
    ],
  },
  {
    key: "b8",
    scope: "GATE",
    gate: "basics",
    kind: "SINGLE",
    topicTag: "gate-basics",
    position: 8,
    prompt: "Which type of donation is described as less complex and can take place regardless of the manner of death?",
    explanation: "Tissue donation (bone, skin, corneas) is less logistically complex than organ donation because tissue can be retrieved hours after circulatory death.",
    verifiedAgainst:
      "Centre for Tissue Engineering (SA tissue bank) published donor criteria",
    choices: [
      { optionKey: "a", position: 0, text: "Tissue donation (e.g. corneas, bone, skin)", isCorrect: true },
      { optionKey: "b", position: 1, text: "Heart transplantation" },
      { optionKey: "c", position: 2, text: "Lung transplantation" },
      { optionKey: "d", position: 3, text: "Liver transplantation" },
    ],
  },
  {
    key: "b9",
    scope: "GATE",
    gate: "basics",
    kind: "SINGLE",
    topicTag: "gate-basics",
    position: 9,
    prompt: "What is the upper age limit for donating tissues like bone, skin, and ligaments?",
    explanation: "Healthy individuals aged between 16 and 80 years can donate bone, skin, and ligaments.",
    verifiedAgainst:
      "Centre for Tissue Engineering (SA tissue bank) published donor criteria",
    choices: [
      { optionKey: "a", position: 0, text: "Up to 80 years", isCorrect: true },
      { optionKey: "b", position: 1, text: "Up to 30 years" },
      { optionKey: "c", position: 2, text: "Up to 50 years" },
      { optionKey: "d", position: 3, text: "There is no limit; even a 100-year-old can donate bone." },
    ],
  },
  {
    key: "b10",
    scope: "GATE",
    gate: "basics",
    kind: "SINGLE",
    topicTag: "gate-basics",
    position: 10,
    prompt: "Is organ donation in South Africa regulated by national laws?",
    explanation: "Donation is strictly controlled under Chapter 8 of the National Health Act No. 61 of 2003.",
    verifiedAgainst:
      "National Health Act 61 of 2003 read directly, plus Regulation 9 of GN R180 of 2 March 2012 via Thomson & Labuschaigne, SAJBL 2024;17(1)",
    choices: [
      { optionKey: "a", position: 0, text: "Yes, it is strictly regulated by the National Health Act.", isCorrect: true },
      { optionKey: "b", position: 1, text: "No, it is governed only by individual hospital policies." },
      { optionKey: "c", position: 2, text: "No, there are no laws governing organ donation." },
      { optionKey: "d", position: 3, text: "Yes, but only for heart transplants." },
    ],
  },
  {
    key: "b11",
    scope: "GATE",
    gate: "basics",
    kind: "SINGLE",
    topicTag: "gate-basics",
    position: 11,
    prompt: "If family consent for organ donation is given over the phone, what is required to make it legal?",
    explanation: "Legislation allows telephonic consent from next of kin provided it is properly witnessed.",
    verifiedAgainst:
      "National Health Act 61 of 2003 read directly, plus Regulation 9 of GN R180 of 2 March 2012 via Thomson & Labuschaigne, SAJBL 2024;17(1)",
    choices: [
      { optionKey: "a", position: 0, text: "The phone call must be verified with witnesses present.", isCorrect: true },
      { optionKey: "b", position: 1, text: "No verification is needed as long as it is recorded." },
      { optionKey: "c", position: 2, text: "Telephonic consent is illegal and never accepted." },
      { optionKey: "d", position: 3, text: "The police commander must listen to the call." },
    ],
  },
  {
    key: "b12",
    scope: "GATE",
    gate: "basics",
    kind: "SINGLE",
    topicTag: "gate-basics",
    position: 12,
    prompt: "Which misconception frequently causes families to refuse organ donation?",
    explanation: "Families often mistakenly believe they are deciding to turn off life support, causing guilt that prevents consent. In reality, brain death means death has already occurred.",
    verifiedAgainst:
      "de Jager et al. SAMJ 2019;109(9):626-631, and Regulation 9 for the independence of the death determination",
    choices: [
      { optionKey: "a", position: 0, text: "Believing they are being asked to personally decide to 'switch off the machines'", isCorrect: true },
      { optionKey: "b", position: 1, text: "Knowing that donation is completely free of charge" },
      { optionKey: "c", position: 2, text: "Understanding that independent doctors certified brain death" },
      { optionKey: "d", position: 3, text: "Knowing that corneas can be donated up to age 70" },
    ],
  },
  {
    key: "b13",
    scope: "GATE",
    gate: "basics",
    kind: "SINGLE",
    topicTag: "gate-basics",
    position: 13,
    prompt: "What support personnel assist families during the FACTS consent communication process?",
    explanation: "The FACTS (Family Approach to Consent for Transplant Strategy) process utilises trauma counsellors, translators, and faith representatives to support families.",
    verifiedAgainst:
      "de Jager et al. SAMJ 2019;109(9):626-631, and Regulation 9 for the independence of the death determination",
    choices: [
      { optionKey: "a", position: 0, text: "Trauma counsellors, translators, and faith representatives", isCorrect: true },
      { optionKey: "b", position: 1, text: "Hospital financial officers and medical insurance brokers" },
      { optionKey: "c", position: 2, text: "Police officers and private attorneys" },
      { optionKey: "d", position: 3, text: "Pharmaceutical sales agents" },
    ],
  },
  {
    key: "b14",
    scope: "GATE",
    gate: "basics",
    kind: "SINGLE",
    topicTag: "gate-basics",
    position: 14,
    prompt: "Can a person with a history of hypertension or diabetes ever be considered for organ donation?",
    explanation: "To address organ scarcity, organs from donors with comorbidities like hypertension or diabetes are evaluated on a case-by-case basis.",
    verifiedAgainst:
      "Organ Donor Foundation donor information; Groote Schuur HIV-positive donor programme; Centre for Tissue Engineering criteria",
    choices: [
      { optionKey: "a", position: 0, text: "Yes, under Extended/Marginal Criteria evaluated case-by-case.", isCorrect: true },
      { optionKey: "b", position: 1, text: "No, high blood pressure immediately disqualifies all organs." },
      { optionKey: "c", position: 2, text: "No, diabetic individuals can only donate skin." },
      { optionKey: "d", position: 3, text: "Only if they are under 18 years old." },
    ],
  },
  {
    key: "b15",
    scope: "GATE",
    gate: "basics",
    kind: "SINGLE",
    topicTag: "gate-basics",
    position: 15,
    prompt: "What is required if a potential donor dies as a result of a motor vehicle accident?",
    explanation: "A motor vehicle accident is an unnatural death, so it must go for a medico-legal post-mortem and organ recovery needs the forensic pathologist\u2019s authorisation in addition to consent. The older term for this role, \u201cdistrict surgeon\u201d, is out of date — it is now the Forensic Pathology Service.",
    verifiedAgainst:
      "National Health Act 61 of 2003 read directly, plus Regulation 9 of GN R180 of 2 March 2012 via Thomson & Labuschaigne, SAJBL 2024;17(1)",
    choices: [
      { optionKey: "a", position: 0, text: "Authorisation from the forensic pathologist, alongside consent", isCorrect: true },
      { optionKey: "b", position: 1, text: "Special permission from the high court magistrate" },
      { optionKey: "c", position: 2, text: "Exemption from family consent laws" },
      { optionKey: "d", position: 3, text: "Written authorisation from the car insurance company" },
    ],
  },
  {
    key: "b16",
    scope: "GATE",
    gate: "basics",
    kind: "SINGLE",
    topicTag: "gate-basics",
    position: 16,
    prompt: "Which professional organisation trains specialised transplant coordinators in South Africa?",
    explanation: "Transplant coordinators are specially trained professionals belonging to the South African Transplant Coordinators Society (SATCS).",
    verifiedAgainst:
      "de Jager et al. SAMJ 2019;109(9):626-631, and Regulation 9 for the independence of the death determination",
    choices: [
      { optionKey: "a", position: 0, text: "South African Transplant Coordinators Society (SATCS)", isCorrect: true },
      { optionKey: "b", position: 1, text: "Health Professions Council of South Africa (HPCSA)" },
      { optionKey: "c", position: 2, text: "Organ Donor Foundation (ODF)" },
      { optionKey: "d", position: 3, text: "World Health Organization (WHO)" },
    ],
  },
  {
    key: "b17",
    scope: "GATE",
    gate: "basics",
    kind: "SINGLE",
    topicTag: "gate-basics",
    position: 17,
    prompt: "Why would heart valves be rejected for tissue donation following a fatal car crash?",
    explanation: "Heart valves are explicitly excluded from tissue donation if the cause of death involved trauma to the heart.",
    verifiedAgainst:
      "Centre for Tissue Engineering (SA tissue bank) published donor criteria",
    choices: [
      { optionKey: "a", position: 0, text: "If the cause of death involved direct heart trauma", isCorrect: true },
      { optionKey: "b", position: 1, text: "Because heart valves can never be donated after accidents" },
      { optionKey: "c", position: 2, text: "If the donor was 25 years old" },
      { optionKey: "d", position: 3, text: "Because tissue donation requires brain death in an ICU" },
    ],
  },
  {
    key: "b18",
    scope: "GATE",
    gate: "basics",
    kind: "SINGLE",
    topicTag: "gate-basics",
    position: 18,
    prompt: "What frequent administrative breakdown prevents potential organ donation from happening?",
    explanation: "A major factor leading to organ loss is the lack of referral — primary hospital staff often fail to alert coordinators when clinical triggers occur.",
    verifiedAgainst:
      "de Jager et al. SAMJ 2019;109(9):626-631, and Regulation 9 for the independence of the death determination",
    choices: [
      { optionKey: "a", position: 0, text: "Medical teams failing to notify coordinators when clinical triggers occur", isCorrect: true },
      { optionKey: "b", position: 1, text: "Transplant coordinators taking too long to answer calls" },
      { optionKey: "c", position: 2, text: "The Organ Donor Foundation refusing referrals" },
      { optionKey: "d", position: 3, text: "Patients signing donor cards without telling their friends" },
    ],
  },
  {
    key: "b19",
    scope: "GATE",
    gate: "basics",
    kind: "SINGLE",
    topicTag: "gate-basics",
    position: 19,
    prompt: "What is the age range for donating corneas?",
    explanation: "Corneas can be donated by individuals aged 6 to 65 years (and up to 70 years in suitable cases).",
    verifiedAgainst:
      "Centre for Tissue Engineering (SA tissue bank) published donor criteria",
    choices: [
      { optionKey: "a", position: 0, text: "Ages 6 to 65 years (up to 70 years)", isCorrect: true },
      { optionKey: "b", position: 1, text: "Ages 18 to 30 years only" },
      { optionKey: "c", position: 2, text: "Ages 50 to 90 years only" },
      { optionKey: "d", position: 3, text: "Infants under 6 months only" },
    ],
  },
  {
    key: "b20",
    scope: "GATE",
    gate: "basics",
    kind: "SINGLE",
    topicTag: "gate-basics",
    position: 20,
    prompt: "What clinical indicator in Cystic Fibrosis (CF) signals that a patient needs a lung transplant?",
    explanation: "Cystic fibrosis indicates lung transplantation when the patient experiences chronic respiratory failure (hypoxia/hypercapnia) alongside a rapidly falling FEV1.",
    verifiedAgainst:
      "Reviewed 23 August 2026 against standard published listing criteria for this organ; thresholds left as stated because they match established practice",
    choices: [
      { optionKey: "a", position: 0, text: "Chronic respiratory failure with hypoxia/hypercapnia and a rapidly falling FEV1", isCorrect: true },
      { optionKey: "b", position: 1, text: "Mild seasonal cough with normal arterial blood gases" },
      { optionKey: "c", position: 2, text: "FEV1 remaining stable above 80% predicted" },
      { optionKey: "d", position: 3, text: "An isolated sinus infection without lung involvement" },
    ],
  },
];
