import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `wrangler types` from wrangler.jsonc — not ours to lint.
    "worker-configuration.d.ts",
    ".open-next/**",
    // Wrangler build scratch.
    ".wrangler/**",
    // Archived artefacts from the Prisma era, kept for reference only.
    "docs/**",
  ]),
]);

export default eslintConfig;
