/**
 * The shape of every row this app reads.
 *
 * Hand-written rather than generated by `supabase gen types`. The generated file
 * covers the whole project — the books, the volunteer roster, the CSR views — and
 * this app has business with fourteen tables of it. Narrow types make the reach
 * of the course obvious in review: if something here names a table outside
 * `learn_*` or `learners`, that is a change worth arguing about.
 *
 * Regenerate the full set for reference with:
 *   cd ../save7-os && supabase gen types typescript --linked --schema public
 *
 * Column names are the database's — snake_case — deliberately unmapped. An
 * automatic camelCase layer would mean every query result had two spellings, one
 * in the SQL and one in the code, and the mismatch would only ever surface at
 * runtime.
 */
import type { LessonKind, LevelTier, ProgressStatus, ResourceType, ReviewStatus, UserRole } from "@/lib/constants";

export type LearnerRow = {
  id: string;
  user_id: string | null;
  email: string;
  first_name: string;
  last_name: string | null;
  name: string;
  volunteer_id: string | null;
  popia_consent_at: string | null;
  active: boolean;
  created_at: string;
  last_seen_at: string | null;
};

export type CourseRow = {
  slug: string;
  title: string;
  subtitle: string | null;
  description: string | null;
  is_published: boolean;
};

export type LevelRow = {
  slug: string;
  position: number;
  title: string;
  tier: LevelTier;
  strapline: string;
  goal: string;
  est_min_minutes: number;
  est_max_minutes: number;
  accent_token: string;
  certificate_title: string;
  certificate_code: string;
  pass_mark_pct: number;
};

export type ModuleRow = {
  slug: string;
  level_slug: string;
  position: number;
  title: string;
  number: number;
  core_question: string;
  intro_markdown: string;
  est_minutes: number;
  is_mandatory: boolean;
};

export type LessonRow = {
  slug: string;
  module_slug: string;
  position: number;
  title: string;
  kind: LessonKind;
  body_markdown: string | null;
  component_key: string | null;
  payload: unknown;
};

export type ResourceRow = {
  slug: string;
  module_slug: string | null;
  title: string;
  description: string | null;
  kind: ResourceType;
  is_required: boolean;
  source: string | null;
  author: string | null;
  published_on: string | null;
  external_url: string | null;
  file_path: string | null;
  licence_note: string | null;
  is_stub: boolean;
  position: number;
};

/** PRE and POST are the matched pair; CHECK is in-lesson; GATE is the volunteer gate. */
export type QuestionScope = "PRE" | "POST" | "CHECK" | "GATE";

export type QuestionRow = {
  id: string;
  authoring_key: string;
  scope: QuestionScope;
  kind: "SINGLE" | "MULTI" | "TRUE_FALSE" | "SCENARIO";
  gate: "clinical" | "basics" | null;
  level_slug: string | null;
  module_slug: string | null;
  prompt: string;
  scenario: string | null;
  explanation: string;
  topic_tag: string;
  difficulty: number;
  pair_key: string | null;
  position: number;
};

/**
 * An option as a browser may see it.
 *
 * **There is no `is_correct` on this type, and that is the point.** The column
 * exists on `learn_choices` and has no read path for any role — the app reads
 * `learn_options_pub`, which omits it, and marking happens in `learn_mark()`,
 * which is security definer. A field here would invite a query that cannot
 * succeed, and a reviewer would have to work out which.
 */
export type OptionRow = {
  question_id: string;
  option_key: string;
  position: number;
  text: string;
};

export type AttemptRow = {
  id: string;
  learner_id: string;
  scope: QuestionScope;
  level_slug: string | null;
  attempt_no: number;
  score_raw: number | null;
  score_max: number | null;
  score_pct: number | null;
  started_at: string;
  submitted_at: string | null;
};

export type AnswerRow = {
  id: string;
  attempt_id: string;
  question_id: string;
  chosen: string[];
  free_text: string | null;
  was_correct: boolean;
};

export type ModuleProgressRow = {
  learner_id: string;
  module_slug: string;
  status: ProgressStatus;
  completed_lessons: string[];
  last_lesson_slug: string | null;
  seconds_spent: number;
  started_at: string;
  updated_at: string;
  /** "Finished reading" — resume and the partial figure read it; nothing completes on it. */
  completed_at: string | null;
  /** First pass of this Stage's quiz (0113). Never cleared once set. */
  quiz_passed_at: string | null;
};

export type LevelProgressRow = {
  learner_id: string;
  level_slug: string;
  status: ProgressStatus;
  percent_complete: number;
  started_at: string;
  updated_at: string;
  completed_at: string | null;
};

export type CourseProgressRow = {
  learner_id: string;
  status: ProgressStatus;
  percent_complete: number;
  baseline_score: number | null;
  baseline_total: number | null;
  baseline_done_at: string | null;
  started_at: string;
  completed_at: string | null;
  updated_at: string;
};

export type CertificateRow = {
  id: string;
  learner_id: string;
  level_slug: string | null;
  /** The public verification code printed on the certificate. */
  code: string;
  issued_name: string;
  award_title: string | null;
  score_pct: number | null;
  issued_at: string;
  revoked_at: string | null;
  revoked_reason: string | null;
};

export type ReviewItemRow = {
  id: string;
  entity_type: "LESSON" | "QUESTION" | "RESOURCE" | "MODULE";
  entity_ref: string;
  location: string;
  claim: string;
  category: "MEDICAL" | "LEGAL" | "STATISTIC";
  status: ReviewStatus;
  severity: number;
  source_hint: string | null;
  cleared_at: string | null;
  cleared_by: string | null;
  notes: string | null;
};

/** What `learn_mark()` returns. The only place an answer key is ever disclosed. */
export type MarkedPaper = {
  attempt: string;
  attempt_no: number;
  score: number;
  total: number;
  pct: number;
  questions: Array<{
    key: string;
    chosen: string[];
    correct: string[];
    ok: boolean;
    why: string;
  }>;
};

/** Re-exported so callers do not import from two places to describe one row. */
export type { ProgressStatus, UserRole };
