/**
 * Write the whole course into a Supabase migration.
 *
 * The backend is Supabase now, and Save7 applies schema and content with
 * `supabase db push`. So the course is loaded the same way everything else on that
 * project is: as a migration, reviewable in a pull request and reproducible on any
 * environment — rather than by a script holding a service-role key, which would
 * mean the content of the course depended on who ran what and when.
 *
 * The authoring files under prisma/content stay the source of truth. This reads
 * them and emits SQL; nothing here decides anything about the course.
 *
 * Run: npx tsx scripts/emit-supabase-content.ts [path-to-save7-os]
 */
import { readdirSync, writeFileSync } from "node:fs";

import { beginnerLevel } from "../prisma/content/level-beginner";
import { intermediateLevel } from "../prisma/content/level-intermediate";
import { advancedLevel } from "../prisma/content/level-advanced";
import { resourceSeeds } from "../prisma/content/resources";
import { questionSeeds } from "../prisma/content/questions";
import { gateQuestions } from "../prisma/content/questions-gate";
import { deriveReviewItems } from "../prisma/content/review";

const OS = process.argv[2] ?? "../save7-os";

/**
 * Where to write.
 *
 * **A content change after the first deploy needs a new migration, not an edit to
 * the old one.** Supabase records a migration as applied by its version prefix, so
 * rewriting `0094_learn_content.sql` changes the repository and nothing on the
 * live project — the file is recorded as done and is never re-run. That mistake is
 * silent: the generator reports the right counts, the diff looks substantial, and
 * the database keeps serving the old content.
 *
 * So the default is the next free number in the migrations directory. Pass an
 * explicit filename as the second argument to overwrite a specific one, which is
 * only correct before that migration has been pushed anywhere.
 */
function nextMigrationPath(): string {
  const dir = `${OS}/supabase/migrations`;
  const highest = readdirSync(dir)
    .map((f) => Number.parseInt(f.slice(0, 4), 10))
    .filter((n) => Number.isFinite(n))
    .reduce((max, n) => Math.max(max, n), 0);
  const version = String(highest + 1).padStart(4, "0");
  return `${dir}/${version}_learn_content.sql`;
}

const OUT = process.argv[3]
  ? `${OS}/supabase/migrations/${process.argv[3]}`
  : nextMigrationPath();

// A second copy, committed to this repository.
//
// The migration's home is save7-os, which is where `supabase db push` runs from.
// But whoever edits the course content is working here, and the generated SQL is
// the only artefact that carries a content change to learners — so a copy lives
// here too, and is committed. It means the current content can be applied by
// anyone with database access (including through the Supabase SQL editor) without
// first having a save7-os checkout, and it makes content changes visible in this
// repository's diffs.
// Named after whichever migration was emitted, not hardcoded: pinning it to 0094
// meant the committed copy claimed to be a migration that had already been applied
// and would never run again.
const LOCAL_OUT = `prisma/supabase/${OUT.split("/").pop()}`;

const levels = [beginnerLevel, intermediateLevel, advancedLevel];

/** SQL literal. Never interpolate anything into this file without going through it. */
function q(v: string | number | boolean | null | undefined): string {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "true" : "false";
  return "'" + v.replace(/'/g, "''") + "'";
}

/** Course questions carry no option key of their own; the gate's are historical. */
const LETTERS = "abcdefghij";

const out: string[] = [];
const counts = { levels: 0, modules: 0, lessons: 0, resources: 0, questions: 0, choices: 0, review: 0 };

out.push(`-- The course content: three levels, their modules and lessons, the reading list,
-- the question bank and the content-review register.
--
-- Re-emitted whenever the authoring files change. Every statement is an upsert
-- keyed on the authoring identifier, so this is safe to apply over an existing
-- course: rows are updated in place and nothing is deleted. A question row deleted
-- and reinserted would take every answer ever recorded against it, and the
-- knowledge-improvement figures with them.
--
-- GENERATED by scripts/emit-supabase-content.ts in the transplant-alchemy repo,
-- from the authoring files under prisma/content. Do not hand-edit: edit the
-- content there and regenerate, or the next regeneration silently reverts you.
--
-- Every statement is an upsert keyed on the authoring identifier — a level's slug,
-- a question's key — so re-running this after a content change updates rows in
-- place. That matters more here than idempotence usually does: a question row that
-- was deleted and reinserted would take every answer ever recorded against it with
-- it, and the improvement figures with those.
--
-- The forty gate questions are in here too, with the option keys the volunteer
-- portal has always sent, so historical volunteer_quiz_attempts.answers keep
-- resolving against them.

begin;

`);

// ── levels, modules, lessons ────────────────────────────────────────────────
for (const [levelIndex, level] of levels.entries()) {
  counts.levels++;
  out.push(`insert into learn_levels (
  slug, position, title, tier, strapline, goal, est_min_minutes, est_max_minutes,
  accent_token, certificate_title, certificate_code, pass_mark_pct
) values (
  ${q(level.slug)}, ${levelIndex}, ${q(level.title)}, ${q(level.tier)},
  ${q(level.strapline)}, ${q(level.goal)}, ${level.estMinMinutes}, ${level.estMaxMinutes},
  ${q(level.accentToken)}, ${q(level.certificateTitle)}, ${q(level.certificateCode)},
  ${level.passMarkPct}
) on conflict (slug) do update set
  position = excluded.position, title = excluded.title, tier = excluded.tier,
  strapline = excluded.strapline, goal = excluded.goal,
  est_min_minutes = excluded.est_min_minutes, est_max_minutes = excluded.est_max_minutes,
  accent_token = excluded.accent_token, certificate_title = excluded.certificate_title,
  certificate_code = excluded.certificate_code, pass_mark_pct = excluded.pass_mark_pct,
  updated_at = now();
`);

  for (const [moduleIndex, mod] of level.modules.entries()) {
    counts.modules++;
    out.push(`insert into learn_modules (
  slug, level_slug, position, title, number, core_question, intro_markdown,
  est_minutes, is_mandatory
) values (
  ${q(mod.slug)}, ${q(level.slug)}, ${moduleIndex}, ${q(mod.title)}, ${mod.number},
  ${q(mod.coreQuestion)}, ${q(mod.introMarkdown)}, ${mod.estMinutes},
  ${q(mod.isMandatory ?? true)}
) on conflict (slug) do update set
  level_slug = excluded.level_slug, position = excluded.position,
  title = excluded.title, number = excluded.number,
  core_question = excluded.core_question, intro_markdown = excluded.intro_markdown,
  est_minutes = excluded.est_minutes, is_mandatory = excluded.is_mandatory,
  updated_at = now();
`);

    for (const [lessonIndex, lesson] of mod.lessons.entries()) {
      counts.lessons++;
      out.push(`insert into learn_lessons (
  slug, module_slug, position, title, kind, body_markdown, component_key, payload
) values (
  ${q(lesson.slug)}, ${q(mod.slug)}, ${lessonIndex}, ${q(lesson.title)}, ${q(lesson.kind)},
  ${q(lesson.bodyMarkdown)}, ${q(lesson.componentKey)},
  ${lesson.payload === undefined ? "NULL" : `${q(JSON.stringify(lesson.payload))}::jsonb`}
) on conflict (module_slug, slug) do update set
  position = excluded.position,
  title = excluded.title, kind = excluded.kind,
  body_markdown = excluded.body_markdown, component_key = excluded.component_key,
  payload = excluded.payload, updated_at = now();
`);
    }
  }
}

// ── the reading list ────────────────────────────────────────────────────────
for (const [index, r] of resourceSeeds.entries()) {
  counts.resources++;
  out.push(`insert into learn_resources (
  slug, module_slug, title, description, kind, is_required, source, author,
  external_url, file_path, licence_note, is_stub, position
) values (
  ${q(r.key)}, ${q(r.moduleSlug)}, ${q(r.title)}, ${q(r.description)}, ${q(r.type)},
  ${q(r.isRequired ?? false)}, ${q(r.source)}, ${q(r.author)}, ${q(r.externalUrl)},
  ${q(r.filePath)}, ${q(r.licenceNote)}, ${q(r.isStub ?? false)}, ${index}
) on conflict (slug) do update set
  module_slug = excluded.module_slug, title = excluded.title,
  description = excluded.description, kind = excluded.kind,
  is_required = excluded.is_required, source = excluded.source,
  author = excluded.author, external_url = excluded.external_url,
  file_path = excluded.file_path, licence_note = excluded.licence_note,
  is_stub = excluded.is_stub, position = excluded.position;
`);
}

/** One question and its options, course or gate. */
function emitQuestion(
  key: string,
  fields: {
    scope: string;
    kind: string;
    gate: string | null;
    levelSlug: string | null;
    moduleSlug: string | null;
    prompt: string;
    scenario: string | null;
    explanation: string;
    topicTag: string;
    difficulty: number;
    pairKey: string | null;
    position: number;
  },
  choices: Array<{ optionKey: string; position: number; text: string; isCorrect: boolean; feedback: string | null }>,
) {
  counts.questions++;
  out.push(`insert into learn_questions (
  authoring_key, scope, kind, gate, level_slug, module_slug, prompt, scenario,
  explanation, topic_tag, difficulty, pair_key, position
) values (
  ${q(key)}, ${q(fields.scope)}, ${q(fields.kind)}, ${q(fields.gate)},
  ${q(fields.levelSlug)}, ${q(fields.moduleSlug)}, ${q(fields.prompt)},
  ${q(fields.scenario)}, ${q(fields.explanation)}, ${q(fields.topicTag)},
  ${fields.difficulty}, ${q(fields.pairKey)}, ${fields.position}
) on conflict (authoring_key) do update set
  scope = excluded.scope, kind = excluded.kind, gate = excluded.gate,
  level_slug = excluded.level_slug, module_slug = excluded.module_slug,
  prompt = excluded.prompt, scenario = excluded.scenario,
  explanation = excluded.explanation, topic_tag = excluded.topic_tag,
  difficulty = excluded.difficulty, pair_key = excluded.pair_key,
  position = excluded.position, updated_at = now();
`);

  for (const c of choices) {
    counts.choices++;
    out.push(`insert into learn_choices (question_id, option_key, position, text, is_correct, feedback)
select id, ${q(c.optionKey)}, ${c.position}, ${q(c.text)}, ${q(c.isCorrect)}, ${q(c.feedback)}
  from learn_questions where authoring_key = ${q(key)}
 on conflict (question_id, option_key) do update set
  position = excluded.position, text = excluded.text,
  is_correct = excluded.is_correct, feedback = excluded.feedback;
`);
  }
}

for (const [index, qs] of questionSeeds.entries()) {
  emitQuestion(
    qs.key,
    {
      scope: qs.scope,
      kind: qs.kind,
      gate: null,
      levelSlug: qs.levelSlug ?? null,
      moduleSlug: qs.moduleSlug ?? null,
      prompt: qs.prompt,
      scenario: qs.scenario ?? null,
      explanation: qs.explanation,
      topicTag: qs.topicTag,
      difficulty: qs.difficulty ?? 1,
      pairKey: qs.pairKey ?? null,
      position: index,
    },
    qs.choices.map((c, i) => ({
      optionKey: LETTERS[i],
      position: i,
      text: c.text,
      isCorrect: c.isCorrect ?? false,
      feedback: c.feedback ?? null,
    })),
  );
}

for (const g of gateQuestions) {
  emitQuestion(
    g.key,
    {
      scope: "GATE",
      kind: g.kind,
      gate: g.gate,
      levelSlug: null,
      moduleSlug: null,
      prompt: g.prompt,
      scenario: null,
      explanation: g.explanation,
      topicTag: g.topicTag,
      difficulty: 1,
      pairKey: null,
      position: g.position,
    },
    g.choices.map((c) => ({
      optionKey: c.optionKey,
      position: c.position,
      text: c.text,
      isCorrect: c.isCorrect ?? false,
      feedback: null,
    })),
  );
}

// ── the content-review register ─────────────────────────────────────────────
// Derived from the content by the same function the seed uses, plus the twenty
// clinical gate items, which assert figures no supplied source backs.
const review = [
  ...deriveReviewItems(),
  ...gateQuestions
    .filter((g) => g.gate === "clinical")
    .map((g) => ({
      entityType: "QUESTION" as const,
      entityRef: g.key,
      location: `volunteer gate · clinical · question ${g.position}`,
      claim: g.prompt,
      category: "MEDICAL" as const,
      severity: 3 as const,
      status: g.verifiedAgainst ? ("APPROVED" as const) : ("NEEDS_VERIFICATION" as const),
      sourceHint:
        g.verifiedAgainst ??
        "Imported from the volunteer portal's generated quiz. No source was supplied with it.",
      notes: g.verifiedAgainst
        ? `Keyed answer and explanation checked against: ${g.verifiedAgainst}`
        : (undefined as string | undefined),
    })),
];

for (const item of review) {
  counts.review++;
  out.push(`insert into learn_review_items (
  entity_type, entity_ref, location, claim, category, severity, status, source_hint, notes
) values (
  ${q(item.entityType)}, ${q(item.entityRef)}, ${q(item.location)}, ${q(item.claim)},
  ${q(item.category)}, ${item.severity ?? 1}, ${q(item.status ?? "NEEDS_VERIFICATION")},
  ${q(item.sourceHint)}, ${q(item.notes)}
) on conflict (entity_type, entity_ref, claim) do update set
  location = excluded.location, category = excluded.category,
  severity = excluded.severity, source_hint = excluded.source_hint,
  notes = excluded.notes,
  -- Only ever promotes an item that is still outstanding. A decision a human has
  -- already recorded -- approved, or rejected -- survives every regeneration,
  -- because silently reverting somebody's sign-off is worse than leaving a stale
  -- row behind.
  status = case
    when learn_review_items.status = 'NEEDS_VERIFICATION' then excluded.status
    else learn_review_items.status
  end;
`);
}

// ── the probe ───────────────────────────────────────────────────────────────
// Counted at generation time and asserted at apply time. A migration that loads
// content silently short is worse than one that fails: the course would simply be
// missing a module and nothing would say so.
out.push(`do $$
declare n int;
begin
  select count(*) into n from learn_levels;
  if n <> ${counts.levels} then raise exception 'expected ${counts.levels} levels, found %', n; end if;
  select count(*) into n from learn_modules;
  if n <> ${counts.modules} then raise exception 'expected ${counts.modules} modules, found %', n; end if;
  select count(*) into n from learn_lessons;
  if n <> ${counts.lessons} then raise exception 'expected ${counts.lessons} lessons, found %', n; end if;
  select count(*) into n from learn_resources;
  if n <> ${counts.resources} then raise exception 'expected ${counts.resources} resources, found %', n; end if;
  select count(*) into n from learn_questions;
  if n <> ${counts.questions} then raise exception 'expected ${counts.questions} questions, found %', n; end if;
  select count(*) into n from learn_questions where scope = 'GATE';
  if n <> 40 then raise exception 'expected 40 gate questions, found %', n; end if;

  /* Every question must have exactly one right answer, except a MULTI, which has
     more than one. A question with none is unanswerable and a SINGLE with two is
     unmarkable — and learn_mark() compares sets, so it would simply mark everyone
     wrong rather than fail loudly. */
  select count(*) into n
    from learn_questions q
    left join learn_choices c on c.question_id = q.id and c.is_correct
   where q.kind <> 'MULTI'
   group by q.id having count(c.id) <> 1
   limit 1;
  if n is not null then raise exception 'a non-MULTI question does not have exactly one correct answer'; end if;
end $$;

select verify_learn_isolation();

commit;
`);

const sql = out.join("\n");
writeFileSync(LOCAL_OUT, sql);
try {
  writeFileSync(OUT, sql);
  console.log(`${OUT}`);
} catch {
  // No save7-os checkout here. The committed copy is still written, which is the
  // one that matters for review; applying it needs that repository or database
  // access either way.
  console.log(`${OUT} not writable — skipped (no save7-os checkout)`);
}
console.log(`${LOCAL_OUT}`);
console.log(counts);
