/**
 * Generate the one-off content import for a brand-new D1 database.
 *
 * A fresh D1 is empty, which is a chicken-and-egg problem: the reseed route needs
 * an admin session, and there are no users yet. So the first load of course
 * content is done with SQL, generated here from the local database that
 * `npm run db:seed` has already produced and that the verification scripts run
 * against.
 *
 * BOOTSTRAP ONLY. This script emits DELETE statements before the inserts, and
 * deleting questions cascades to QuizAnswer — so running it against a live course
 * would destroy learner results. Once the course is live, content updates go
 * through POST /api/admin/reseed, which upserts and preserves learner data.
 *
 * Learner tables are deliberately not exported: no User, QuizAttempt, QuizAnswer,
 * ModuleProgress, LevelProgress, CourseProgress, Certificate or EventLog. Nobody's
 * personal data goes into a file that gets committed and piped through a CLI.
 */
import "dotenv/config";
import { writeFileSync } from "node:fs";
import Database from "better-sqlite3";

/** Parents before children, so the inserts satisfy foreign keys. */
const CONTENT_TABLES = [
  "Course",
  "Level",
  "Module",
  "Lesson",
  "Resource",
  "Question",
  "Choice",
  "ContentReviewItem",
] as const;

const OUT = "prisma/d1-bootstrap/0001_content.sql";

function quote(value: unknown): string {
  if (value === null) return "NULL";
  if (typeof value === "number") return String(value);
  if (value instanceof Buffer) return `X'${value.toString("hex")}'`;
  return `'${String(value).replace(/'/g, "''")}'`;
}

function main() {
  const db = new Database(process.env.DATABASE_URL!.replace(/^file:/, ""), {
    readonly: true,
  });

  const lines: string[] = [
    "-- Transplant Alchemy 101 — course content.",
    "--",
    "-- Generated by scripts/export-d1-content.ts from the local database. Do not",
    "-- hand-edit: change the files in prisma/content and re-run the generator.",
    "--",
    "-- BOOTSTRAP ONLY: the DELETEs below cascade to learner answers. Use",
    "-- POST /api/admin/reseed to update content on a live course.",
    "",
  ];

  // Children first when clearing, so nothing is orphaned mid-script.
  for (const table of [...CONTENT_TABLES].reverse()) {
    lines.push(`DELETE FROM "${table}";`);
  }
  lines.push("");

  let total = 0;
  for (const table of CONTENT_TABLES) {
    const rows = db.prepare(`SELECT * FROM "${table}"`).all() as Record<string, unknown>[];
    if (rows.length === 0) continue;

    // Review decisions are reset on export. `reviewedById` points at a User row,
    // and users are not exported — so it would be a dangling foreign key. More to
    // the point, an approval recorded by a developer on a test database is not a
    // sign-off by Save7's clinical or legal reviewer, and shipping it as one would
    // defeat the entire purpose of the register.
    if (table === "ContentReviewItem") {
      for (const row of rows) {
        row.status = "NEEDS_VERIFICATION";
        row.reviewedById = null;
        row.reviewedAt = null;
      }
    }

    const columns = Object.keys(rows[0]);
    const columnList = columns.map((c) => `"${c}"`).join(", ");

    lines.push(`-- ${table}: ${rows.length} rows`);
    for (const row of rows) {
      const values = columns.map((c) => quote(row[c])).join(", ");
      lines.push(`INSERT INTO "${table}" (${columnList}) VALUES (${values});`);
    }
    lines.push("");
    total += rows.length;
    console.log(`  ${table.padEnd(20)} ${rows.length}`);
  }

  writeFileSync(OUT, lines.join("\n"));
  console.log(`\n  ${total} rows → ${OUT}`);
  db.close();
}

main();
